name: Falcon Container Sensor Pull

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  pull-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub (or your Docker registry)
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Download the Falcon Container Sensor Pull script
        run: |
          curl https://raw.githubusercontent.com/yannhowe/falcon-scripts/main/bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh --output falcon-container-sensor-pull.sh
          chmod +x falcon-container-sensor-pull.sh

      - name: Pull Falcon Sensor for Linux (daemonset)
        run: |
          ./falcon-container-sensor-pull.sh \
          --cid ${{ secrets.FALCON_CID }} \
          --client-id ${{ secrets.FALCON_CLIENT_ID }} \
          --client-secret ${{ secrets.FALCON_CLIENT_SECRET }} \
          --region ${{ secrets.FALCON_REGION }} \
          --node

      - name: Pull Falcon Container Sensor for Linux (sidecar)
        run: |
          ./falcon-container-sensor-pull.sh \
          --cid ${{ secrets.FALCON_CID }} \
          --client-id ${{ secrets.FALCON_CLIENT_ID }} \
          --client-secret ${{ secrets.FALCON_CLIENT_SECRET }} \
          --region ${{ secrets.FALCON_REGION }}
